config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'matches#home'
  get '/matches/general_report', to: 'matches#general_report'
  get '/matches/death_cause_report', to: 'matches#death_cause_report'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/kill_countable.rb
# frozen_string_literal: true

module KillCountable
  extend ActiveSupport::Concern

  def total_kills
    total_kills = kills.count
    total_kills -= deaths_relation.by_world.count
    total_kills
  end

  def deaths_relation
    respond_to?(:deaths) ? deaths : kills
  end
end

app/models/kill.rb
# frozen_string_literal: true

class Kill < ApplicationRecord
  belongs_to :killer, class_name: 'Player', foreign_key: 'killer_id', optional: true
  belongs_to :victim, class_name: 'Player', foreign_key: 'victim_id'
  belongs_to :match

  scope :by_world, -> { where(killer: nil) }

  enum cause_of_death: {
    MOD_UNKNOWN: 'MOD_UNKNOWN',
    MOD_SHOTGUN: 'MOD_SHOTGUN',
    MOD_GAUNTLET: 'MOD_GAUNTLET',
    MOD_MACHINEGUN: 'MOD_MACHINEGUN',
    MOD_GRENADE: 'MOD_GRENADE',
    MOD_GRENADE_SPLASH: 'MOD_GRENADE_SPLASH',
    MOD_ROCKET: 'MOD_ROCKET',
    MOD_ROCKET_SPLASH: 'MOD_ROCKET_SPLASH',
    MOD_PLASMA: 'MOD_PLASMA',
    MOD_PLASMA_SPLASH: 'MOD_PLASMA_SPLASH',
    MOD_RAILGUN: 'MOD_RAILGUN',
    MOD_LIGHTNING: 'MOD_LIGHTNING',
    MOD_BFG: 'MOD_BFG',
    MOD_BFG_SPLASH: 'MOD_BFG_SPLASH',
    MOD_WATER: 'MOD_WATER',
    MOD_SLIME: 'MOD_SLIME',
    MOD_LAVA: 'MOD_LAVA',
    MOD_CRUSH: 'MOD_CRUSH',
    MOD_TELEFRAG: 'MOD_TELEFRAG',
    MOD_FALLING: 'MOD_FALLING',
    MOD_SUICIDE: 'MOD_SUICIDE',
    MOD_TARGET_LASER: 'MOD_TARGET_LASER',
    MOD_TRIGGER_HURT: 'MOD_TRIGGER_HURT',
    MOD_NAIL: 'MOD_NAIL',
    MOD_CHAINGUN: 'MOD_CHAINGUN',
    MOD_PROXIMITY_MINE: 'MOD_PROXIMITY_MINE',
    MOD_KAMIKAZE: 'MOD_KAMIKAZE',
    MOD_JUICED: 'MOD_JUICED',
    MOD_GRAPPLE: 'MOD_GRAPPLE'
  }
end

app/models/log/extractor.rb
# frozen_string_literal: true

module Log
  class Extractor
    class << self
      def game_name(row)
        row.match(/gamename\\([^\\]+)/)&.captures&.first
      end

      def player_name(row)
        row.match(/n\\(.*?)\\t/)&.captures&.first
      end

      def kill_info(row)
        match_data = row.match(/Kill: \d+ \d+ \d+: (.+?) killed (.+?) by (.+)/)
        match_data&.captures || []
      end
    end
  end
end

app/models/log/parser.rb
# frozen_string_literal: true

module Log
  class Parser
    attr_reader :file

    def initialize(file)
      @file = file
      @match = nil
    end

    def call
      @file.each do |row|
        @row = row
        if row.include?('InitGame')
          create_match
        elsif row.include?('ClientUserinfoChanged')
          create_player
        elsif row.include?('Kill')
          create_kill
        end
      end
    end

    private

    def create_match
      @match = Match.create(name: Extractor.game_name(@row))
    end

    def create_player
      player_name = Extractor.player_name(@row)
      player = Player.find_or_create_by(name: player_name)

      @match.players << player if @match
    end

    def create_kill
      killer_name, victim_name, cause_of_death = Extractor.kill_info(@row)
      killer = killer_name != '<world>' ? Player.find_by(name: killer_name) : nil
      victim = Player.find_by(name: victim_name)

      Kill.create(
        match: @match,
        killer:,
        victim:,
        cause_of_death:
      )
    end
  end
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  include KillCountable

  has_many :kills, dependent: :destroy
  has_many :match_players
  has_many :players, through: :match_players

  def kills_by_means
    { kills_by_means: kills.group(:cause_of_death).count }
  end
end

app/models/match_player.rb
# frozen_string_literal: true

class MatchPlayer < ApplicationRecord
  belongs_to :match
  belongs_to :player
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  include KillCountable

  has_many :kills, class_name: 'Kill', foreign_key: 'killer_id', dependent: :destroy
  has_many :deaths, class_name: 'Kill', foreign_key: 'victim_id', dependent: :destroy
  has_many :match_players
  has_many :matches, through: :match_players

  def total_kills_in_match(match)
    total_kills = kills.where(match:).count
    total_kills -= deaths.by_world.where(match:).count
    total_kills
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < ApplicationController
  before_action :setup_top_killers, only: %i[general_report]
  before_action :setup_top_causes, only: %i[death_cause_report]

  def index; end

  def general_report
    @matches = Match.includes(:kills, :match_players, match_players: [:player]).all

    respond_to do |format|
      format.html
      format.json
    end
  end

  def death_cause_report
    @matches = Match.includes(:kills).all

    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def setup_top_causes
    @top_causes = Kill.select('cause_of_death, COUNT(*) AS count')
                      .group(:cause_of_death)
                      .order('count DESC')
                      .limit(3)
  end

  def setup_top_killers
    @top_killers = Player.left_joins(:kills)
                         .group('players.id')
                         .select('players.*, COUNT(kills.id) as total_kills')
                         .order('total_kills DESC')
                         .limit(3)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def nav_link(text, path)
    class_name = current_page?(path) ? 'active' : ''

    content_tag(:div, class: 'menu') do
      link_to(text, path, class: class_name)
    end
  end
end

app/views/layouts/_header.html.erb
<div class="header">
  <div class="logo-header">
    <%= link_to root_path do %>
      <%= image_tag('mini-logo-red.png', class: 'logo-image-header') %>
    <% end %>
  </div>
  <div class="menus">
    <%= nav_link('Match Score', matches_general_report_path) %>
    <span class="text-red">|</span>
    <%= nav_link('Death Cause', matches_death_cause_report_path) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuakeReports</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css' %>
  </head>

  <body class="no-margin">
    <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/matches/death_cause_report.html.erb
<div class="margin-30">
  <h1>Death Cause</h1>
  <div class="centered">
    <h2>Top Causes</h2>
    <div class="podium">
      <div class="trophy trophy-gold">
        <i class="fa-solid fa-skull-crossbones gold"></i>
        <span class="font-size-20 bold"><%= t("cause_of_death.#{@top_causes.first.cause_of_death}") %></span>
        <span>Total Kills: <%= @top_causes.first.count %></span>
      </div>
      <div class="trophy trophy-silver">
        <i class="fa-solid fa-skull-crossbones silver"></i>
        <span class="font-size-20 bold"><%= t("cause_of_death.#{@top_causes.second.cause_of_death}") %></span>
        <span>Total Kills: <%= @top_causes.second.count %></span>
      </div>
      <div class="trophy trophy-bronze">
        <i class="fa-solid fa-skull-crossbones bronze"></i>
        <span class="font-size-20 bold"><%= t("cause_of_death.#{@top_causes.third.cause_of_death}") %></span>
        <span>Total Kills: <%= @top_causes.third.count %></span>
      </div>
    </div> 
  </div>
  <table class="custom-table">
    <tr>
      <th>Match</th>
      <th>Death Cause</th>
    </tr>
      <% @matches.each do |match| %>
        <tr>
          <td><%= match.name %></td>
          <td><%= match.kills.group(:cause_of_death).count.map { |k,v| "#{k}: #{v}"}.join(' | ') %></td>
        </tr>
      <% end %>      
    </tr>
</div>

app/views/matches/general_report.html.erb
<div class="margin-30">
  <h1>Match Score</h1>
  <div class="centered">
    <h2>Top Players</h2>
    <div class="podium">
      <div class="trophy trophy-gold">
        <i class="fa-solid fa-trophy gold"></i>
        <span class="font-size-20 bold"><%= @top_killers.first.name %></span>
        <span>Total Score: <%= @top_killers.first.total_kills %></span>
      </div>
      <div class="trophy trophy-silver">
        <i class="fa-solid fa-trophy silver"></i>
        <span class="font-size-20 bold"><%= @top_killers.second.name %></span>
        <span>Total Score: <%= @top_killers.second.total_kills %></span>
      </div>
      <div class="trophy trophy-bronze">
        <i class="fa-solid fa-trophy bronze"></i>
        <span class="font-size-20 bold"><%= @top_killers.third.name %></span>
        <span>Total Score: <%= @top_killers.third.total_kills %></span>
      </div>
    </div> 
  </div>
  <table class="custom-table">
    <tr>
      <th>Match</th>
      <th>Total Kills</th>
      <th>Players</th>
      <th>Players Score</th>
    </tr>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.name %></td>
        <td><%= match.kills.count %></td>
        <td><%= match.players.pluck(:name).uniq.join(' | ') %></td>
        <td><%= match.players.uniq.map { |player| "#{player.name}: #{player.total_kills_in_match(match)}" }.join(' | ') %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/matches/home.html.erb
<div class="logo-container">
  <%= image_tag('logo.png', alt: 'Logo', class: 'logo') %>
</div>

<div class="centered">
  <%= link_to 'Match Score', matches_general_report_path, class: 'rounded-button' %>
  <%= link_to 'Death Cause', matches_death_cause_report_path, class: 'rounded-button' %>
</div>